# application.yml
server:
#  port: ${PORT}
  servlet:
    context-path: "/pathfinders"

spring:
  application:
    name: pathfinders
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: ${DATASOURCE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    thymeleaf:
      cache: true