spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbvfinanceiro
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: "/pathfinders"