spring:
  datasource:
#    url: jdbc:postgresql://localhost:3306/dbvfinanceiro
    url: ${DATABASE_URL}
    #username: root
    #password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true

server:
  #port: 8080
  servlet:
    context-path: "/pathfinders"