spring:
  datasource:
#    url: jdbc:postgresql://localhost:3306/dbvfinanceiro
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/dbvfinanceiro}
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: false
    show-sql: true
  thymeleaf:
    cache: true

server:
  #port: 8080
  servlet:
    context-path: "/pathfinders"